version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=your_postgres_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - db
      - redis
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '8080:80'
    environment:
      - REACT_APP_API_URL=http://backend:3000
    depends_on:
      - backend
  mobile:
    build:
      context: ./mobile
      dockerfile: Dockerfile
    ports:
      - '19000:19000'
      - '19001:19001'
      - '19002:19002'
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=your_ip_address
      - REACT_APP_API_URL=http://backend:3000
    depends_on:
      - backend
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=your_postgres_user
      - POSTGRES_PASSWORD=your_postgres_password
      - POSTGRES_DB=your_postgres_db
    volumes:
      - ./backend/data:/var/lib/postgresql/data
  redis:
    image: redis:latest
    volumes:
      - ./backend/redis:/data